name: "sql_transformations"
version: "1.0.0"
config-version: 2

profile: "sql_transformations"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  env: "dev"
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/
models:
  +materialized: table